# Build and publish the production container image with Podman.
#
# Dedicated makefile (invoke with `make -f image.mk <target>`) so it does not
# collide with the EUMM `Makefile` generated by `perl Makefile.PL`.
#
# Usage:
#   make -f image.mk build
#   make -f image.mk push    REGISTRY=ghcr.io IMAGE=gonzalo-radio/resque-web TAG=0.1.0
#   make -f image.mk release REGISTRY=ghcr.io IMAGE=gonzalo-radio/resque-web TAG=0.1.0
#   make -f image.mk login   REGISTRY=ghcr.io
#
# Publish to any public or private registry after `podman login <REGISTRY>`.

REGISTRY ?= localhost
IMAGE    ?= resque-web
VERSION  ?= 0.1.0
TAG      ?= $(VERSION)
PLATFORM ?= linux/amd64
REF      := $(REGISTRY)/$(IMAGE)

# Extra flags forwarded to podman push (e.g. PUSH_FLAGS=--tls-verify=false for a
# local test registry).
PUSH_FLAGS ?=

.DEFAULT_GOAL := help
.PHONY: help build push release login

help:
	@echo "resque-web image builder (podman)"
	@echo
	@echo "Targets:"
	@echo "  build    Build $(REF):$(TAG) and $(REF):latest ($(PLATFORM))"
	@echo "  push     Push $(REF):$(TAG) and $(REF):latest"
	@echo "  release  build + push"
	@echo "  login    podman login $(REGISTRY)"
	@echo
	@echo "Vars (override on the command line):"
	@echo "  REGISTRY=$(REGISTRY)  IMAGE=$(IMAGE)  VERSION=$(VERSION)  TAG=$(TAG)  PLATFORM=$(PLATFORM)"
	@echo "  Resulting ref: $(REF):$(TAG)"

build:
	podman build \
		--format docker \
		--platform $(PLATFORM) \
		--build-arg VERSION=$(VERSION) \
		-t $(REF):$(TAG) \
		-t $(REF):latest \
		-f Containerfile .

push:
	podman push $(PUSH_FLAGS) $(REF):$(TAG)
	podman push $(PUSH_FLAGS) $(REF):latest

release: build push

login:
	podman login $(REGISTRY)
